version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  Checkout:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run: mkdir /tmp/source_code
      - checkout
      - run: cp -a . /tmp/source_code
      - persist_to_workspace:
          root: /tmp
          paths:
            - source_code
  Security Scan:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: /tmp
      - run: echo 'Scan Completed - No vulnerabilities found.'
  Build Docker Image:
    machine:
      image: ubuntu-2004:202107-01
#    docker:
#      - image: cimg/base:2021.07
    environment:
      AWS_ECR_ACCOUNT_URL: 050400155701.dkr.ecr.us-east-1.amazonaws.com
    working_directory: /tmp/source_code
    steps:
      - attach_workspace:
          at: /tmp
      - aws-ecr/build-image:
          repo: marcin-cicd-demo
          tag: '210802-f8af15a'
      - run:
  Unit Test:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: /tmp
      - run: echo 'Unit Test Completed - No issues found.'

workflows:
  version: 2
  build-test:
    jobs:
      - checkout
      - security_scan:
          requires:
            - checkout
      - build_image:
          requires:
            - security_scan
      - Unit Test:
          requires:
            - build_image

