version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  Checkout:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run: mkdir /tmp/source_code
      - checkout
      - run: cp -a . /tmp/source_code
      - persist_to_workspace:
          root: /tmp
          paths:
            - source_code
  Security Scan:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: /tmp
      - run: echo 'Scan Completed - No vulnerabilities found.'
  Build Docker Image:
    machine:
      image: ubuntu-2004:202107-01
#    docker:
#      - image: cimg/base:2021.07
    environment:
      AWS_ECR_ACCOUNT_URL: 050400155701.dkr.ecr.us-east-1.amazonaws.com
    working_directory: /tmp/source_code
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Get Current Date and Commit for Image Tag
          command: |
            COMMIT=`git rev-parse --short HEAD | tr -d "\n"`
            echo ${COMMIT}
            DATE=`date +"%y%m%d"`
            echo ${DATE}
            echo "export DATE=${DATE}" >> $BASH_ENV
            echo "export COMMIT=${COMMIT}" >> $BASH_ENV
      - aws-ecr/build-image:
          repo: marcin-cicd-demo
          tag: "${DATE}-${COMMIT}"
      - run:
          name: Save Created Image to workspace
          command: |
            docker images
            docker save -o /tmp/source_code/image.tar ${AWS_ECR_ACCOUNT_URL}/marcin-cicd-demo:${DATE}-${COMMIT}
            ls -la
      - persist_to_workspace:
          root: /tmp
          paths:
            - source_code
  Unit Test:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: /tmp
      - run: echo 'Unit Test Completed - No issues found.'
  Push Image to ECR:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: /tmp
      - setup_remote_docker:
          version: 20.10.06
          docker_layer_caching: true
      - run:
          name: Load Image from workspace
          command: |
            ls -la /tmp/source_code/
            docker load -i /tmp/source_code/image.tar
            docker images

workflows:
  version: 2
  build-test:
    jobs:
      - Checkout
      - Security Scan:
          requires:
            - Checkout
      - Build Docker Image:
          requires:
            - Security Scan
      - Unit Test:
          requires:
            - Build Docker Image
      - Push Image to ECR:
          requires:
            - Unit Test


